// <auto-generated />
using System;
using Clean_Architecture_Soufiane.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clean_Architecture_Soufiane.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.HasSequence("venteitemseq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("venteseq")
                .IncrementsBy(10);

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseHiLo("venteseq");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("_venteDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("VenteDate");

                    b.Property<int>("_venteStatusId")
                        .HasColumnType("int")
                        .HasColumnName("VenteStatusId");

                    b.HasKey("Id");

                    b.HasIndex("_venteStatusId");

                    b.ToTable("Vte_vente");
                });

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.VenteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseHiLo("venteitemseq");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("VenteId")
                        .HasColumnType("int");

                    b.Property<decimal>("_discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Discount");

                    b.Property<string>("_pictureUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PictureUrl");

                    b.Property<string>("_productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductName");

                    b.Property<decimal>("_unitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("UnitPrice");

                    b.Property<int>("_units")
                        .HasColumnType("int")
                        .HasColumnName("Units");

                    b.HasKey("Id");

                    b.HasIndex("VenteId");

                    b.ToTable("venteItems");
                });

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.VenteStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("orderstatus");
                });

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.Vente", b =>
                {
                    b.HasOne("Clean_Architecture_Soufiane.Domain.AggregatesModel.VenteStatus", "VenteStatus")
                        .WithMany()
                        .HasForeignKey("_venteStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenteStatus");
                });

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.VenteItem", b =>
                {
                    b.HasOne("Clean_Architecture_Soufiane.Domain.AggregatesModel.Vente", null)
                        .WithMany("VenteItems")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clean_Architecture_Soufiane.Domain.AggregatesModel.Vente", b =>
                {
                    b.Navigation("VenteItems");
                });
#pragma warning restore 612, 618
        }
    }
}
